repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: check-commit-message
        name: Check Commit Message Format
        entry: python check_commit_msg.py
        language: python
        stages: [commit-msg]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        name: Lint with ruff
        language: python
        entry: ruff check
        types: [python]
