- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ web_packages }}"
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

- name: Start and enable web server
  service:
    name: "{{ web_service }}"
    state: started
    enabled: yes
