- name: Install database server
  package:
    name: "{{ db_package }}"
    state: present

- name: Start and enable database service
  service:
    name: "{{ db_service }}"
    state: started
    enabled: yes

- name: Create database
  mysql_db:
    name: myapp_db
    state: present

- name: Create database user
  mysql_user:
    name: myapp_user
    password: myapp_password
    priv: "myapp_db.*:ALL"
    state: present
