---
- name: Install necessary system packages for Flask app
  hosts: all
  become: true
  tasks:
    - name: Install Python and pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
    - name: Install Flask
      pip:
        name: flask
        state: present
